import importlib.util
import sys
from pathlib import Path

import pytest

_GEN_PATH = Path(__file__).resolve().parent.parent / "scripts" / "generate_fixtures.py"
_spec = importlib.util.spec_from_file_location("generate_fixtures", _GEN_PATH)
_generate_fixtures = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_generate_fixtures)

# generate_corpus.py uses @dataclass, whose field-type resolution looks up
# sys.modules[cls.__module__] -- module_from_spec() doesn't register the module there on its
# own, so it must be registered before exec_module() runs (same fix already applied once in
# tests/test_generate_corpus.py; found needed here too, 2026-08-20, once corpus/ generation
# was pulled into conftest.py for the first time).
_CORPUS_GEN_PATH = Path(__file__).resolve().parent.parent / "scripts" / "generate_corpus.py"
_corpus_spec = importlib.util.spec_from_file_location("generate_corpus", _CORPUS_GEN_PATH)
_generate_corpus = importlib.util.module_from_spec(_corpus_spec)
sys.modules["generate_corpus"] = _generate_corpus
_corpus_spec.loader.exec_module(_generate_corpus)


@pytest.fixture(scope="session", autouse=True)
def _build_fixtures() -> None:
    """Regenerate fixtures once per test session so they're always in sync with the generator."""
    _generate_fixtures.main()


@pytest.fixture(scope="session", autouse=True)
def _build_corpus() -> None:
    """Regenerate corpus/ once per test session -- mirrors _build_fixtures above. Found missing
    2026-08-20: corpus/ is gitignored and was only ever generated by hand, once, long ago, then
    left on disk locally -- every corpus-dependent test silently depended on that leftover
    directory rather than on anything the test suite itself guaranteed. Invisible until a genuinely
    fresh checkout (CI's first-ever run) tried the suite and every corpus-dependent test failed
    with "No corpus entries found". generate_corpus.main() is idempotent (deterministic content,
    no randomness), so regenerating it every session is safe and cheap.
    """
    _generate_corpus.main()


@pytest.fixture
def fixtures_dir() -> Path:
    return _generate_fixtures.FIXTURES_DIR
